import { Skill } from "../types";
import { inferCategory } from "../categories";

function skill(
  name: string,
  source: string,
  installs: number,
  description: string,
  tags: readonly string[] = []
): Skill {
  const owner = source.split("/")[0];
  const isOfficial = ["vercel-labs", "anthropics", "vercel"].includes(owner);
  const isVerified = installs >= 10000 || ["remotion-dev", "expo", "supabase", "better-auth", "google-labs-code", "google-gemini", "cloudflare", "stripe", "coinbase", "railwayapp"].includes(owner);

  return {
    id: `${source}/${name}`,
    name,
    description,
    homepage: `https://skills.sh/${source}`,
    repoUrl: `https://github.com/${source}`,
    tags,
    category: inferCategory(name, owner, tags),
    installCommand: `npx skills add ${source}`,
    updatedAt: "2026-02-13",
    source,
    badge: isOfficial ? "official" : isVerified ? "verified" : "community",
    installs,
    owner,
  };
}

// Skills from ranks ~200-350 on skills.sh
export const skillsExtra1: readonly Skill[] = [
  skill("kpi-dashboard-design", "wshobson/agents", 1800, "Design data-driven KPI dashboards with clear metrics hierarchy and actionable insights.", ["dashboard", "kpi", "data-viz"]),
  skill("deployment-pipeline-design", "wshobson/agents", 1800, "Design robust deployment pipelines with staging, canary releases, and rollback strategies.", ["deployment", "ci-cd", "pipeline"]),
  skill("changelog-automation", "wshobson/agents", 1800, "Automate changelog generation from commits and PRs with conventional commit parsing.", ["changelog", "automation", "git"]),
  skill("code-review-expert", "sanyuan0704/code-review-expert", 1700, "Expert-level code review with focus on architecture, patterns, and maintainability.", ["code-review", "quality", "patterns"]),
  skill("vue-pinia-best-practices", "vuejs-ai/skills", 1700, "Pinia state management best practices for Vue 3 applications.", ["vue", "pinia", "state-management"]),
  skill("obsidian-markdown", "kepano/obsidian-skills", 1700, "Write and manage Obsidian-compatible markdown with plugins and linking conventions.", ["obsidian", "markdown", "knowledge"]),
  skill("react-email", "resend/react-email", 1700, "Build beautiful, responsive emails using React components with Resend integration.", ["react", "email", "components"]),
  skill("simplify", "brianlovin/claude-config", 1700, "Simplify complex code and reduce unnecessary abstraction for better readability.", ["refactoring", "simplicity", "code-quality"]),
  skill("data-storytelling", "wshobson/agents", 1700, "Transform data analysis into compelling narratives with clear visualizations.", ["data", "storytelling", "visualization"]),
  skill("gitlab-ci-patterns", "wshobson/agents", 1700, "Configure GitLab CI/CD pipelines with stages, caching, and deployment patterns.", ["gitlab", "ci-cd", "devops"]),
  skill("openapi-spec-generation", "wshobson/agents", 1700, "Generate OpenAPI 3.0 specifications from code or natural language descriptions.", ["openapi", "api", "specification"]),
  skill("workflow-orchestration-patterns", "wshobson/agents", 1700, "Design workflow orchestration with saga, choreography, and state machine patterns.", ["workflow", "orchestration", "patterns"]),
  skill("secrets-management", "wshobson/agents", 1700, "Manage application secrets with vaults, rotation policies, and secure injection.", ["security", "secrets", "vault"]),
  skill("terraform-module-library", "wshobson/agents", 1700, "Build reusable Terraform modules for infrastructure as code with best practices.", ["terraform", "iac", "devops"]),
  skill("grafana-dashboards", "wshobson/agents", 1600, "Create Grafana monitoring dashboards with PromQL queries and alert rules.", ["grafana", "monitoring", "observability"]),
  skill("swift-concurrency", "avdlee/swift-concurrency-agent-skill", 1600, "Master Swift structured concurrency with async/await, actors, and task groups.", ["swift", "concurrency", "ios"]),
  skill("react-modernization", "wshobson/agents", 1600, "Modernize legacy React codebases with hooks, server components, and current patterns.", ["react", "modernization", "refactoring"]),
  skill("create-adaptable-composable", "vuejs-ai/skills", 1600, "Build flexible Vue composables that adapt to different use cases and contexts.", ["vue", "composables", "patterns"]),
  skill("godot-gdscript-patterns", "wshobson/agents", 1600, "Write clean GDScript for Godot Engine with scene patterns and signal management.", ["godot", "gdscript", "gamedev"]),
  skill("vue-testing-best-practices", "antfu/skills", 1600, "Test Vue applications effectively with Vitest, Vue Test Utils, and snapshot testing.", ["vue", "testing", "vitest"]),
  skill("dotnet-backend-patterns", "wshobson/agents", 1600, "Build .NET backend services with clean architecture, middleware, and EF Core patterns.", ["dotnet", "csharp", "backend"]),
  skill("solidity-security", "wshobson/agents", 1600, "Audit and secure Solidity smart contracts against common vulnerabilities and exploits.", ["solidity", "security", "web3"]),
  skill("git-commit", "github/awesome-copilot", 1600, "Write clear, conventional git commit messages with proper scope and descriptions.", ["git", "commit", "conventions"]),
  skill("writing-clearly-and-concisely", "softaworks/agent-toolkit", 1600, "Write clear, concise prose by eliminating jargon, passive voice, and redundancy.", ["writing", "communication", "clarity"]),
  skill("agent-md-refactor", "softaworks/agent-toolkit", 1600, "Refactor agent markdown files for better structure, clarity, and maintainability.", ["markdown", "refactoring", "agent"]),
  skill("mermaid-diagrams", "softaworks/agent-toolkit", 1600, "Generate Mermaid diagrams for flowcharts, sequence diagrams, and architecture views.", ["mermaid", "diagrams", "visualization"]),
  skill("vue-development-guides", "vuejs-ai/skills", 1600, "Comprehensive Vue.js development guides covering setup, patterns, and ecosystem.", ["vue", "guides", "development"]),
  skill("commit-work", "softaworks/agent-toolkit", 1600, "Manage work commits with structured messages, change tracking, and review prep.", ["git", "commit", "workflow"]),
  skill("remotion", "google-labs-code/stitch-skills", 1600, "Create programmatic videos with Remotion integrated into Google's Stitch workflow.", ["remotion", "video", "stitch"]),
  skill("frontend-code-review", "langgenius/dify", 1600, "Review frontend code with focus on component patterns, performance, and accessibility.", ["code-review", "frontend", "quality"]),
  skill("crafting-effective-readmes", "softaworks/agent-toolkit", 1600, "Write effective README files with clear structure, examples, and installation guides.", ["readme", "documentation", "writing"]),
  skill("qa-test-planner", "softaworks/agent-toolkit", 1600, "Plan comprehensive QA test strategies with test cases, coverage, and automation.", ["qa", "testing", "planning"]),
  skill("session-handoff", "softaworks/agent-toolkit", 1600, "Hand off agent sessions cleanly with context preservation and task continuity.", ["agent", "handoff", "context"]),
  skill("codex", "softaworks/agent-toolkit", 1600, "Optimize prompts and workflows for OpenAI Codex integration in development.", ["codex", "ai", "prompts"]),
  skill("gemini", "softaworks/agent-toolkit", 1600, "Configure and optimize Google Gemini model integrations for agent workflows.", ["gemini", "ai", "google"]),
  skill("meme-factory", "softaworks/agent-toolkit", 1600, "Generate memes with text overlays, templates, and custom image compositions.", ["meme", "creative", "fun"]),
  skill("llm-evaluation", "wshobson/agents", 1600, "Evaluate LLM outputs with scoring rubrics, benchmarks, and quality metrics.", ["llm", "evaluation", "ai"]),
  skill("skill-judge", "softaworks/agent-toolkit", 1600, "Evaluate and score skill quality based on structure, clarity, and completeness.", ["skills", "evaluation", "quality"]),
  skill("dependency-updater", "softaworks/agent-toolkit", 1600, "Safely update project dependencies with compatibility checking and migration support.", ["dependencies", "updates", "maintenance"]),
  skill("domain-name-brainstormer", "softaworks/agent-toolkit", 1600, "Generate creative domain name ideas based on keywords, brand, and availability.", ["domain", "naming", "brainstorming"]),
  skill("reducing-entropy", "softaworks/agent-toolkit", 1600, "Reduce codebase entropy through systematic cleanup, simplification, and documentation.", ["refactoring", "cleanup", "entropy"]),
  skill("daily-meeting-update", "softaworks/agent-toolkit", 1600, "Generate structured daily standup updates from recent commits and task progress.", ["standup", "meetings", "updates"]),
  skill("ship-learn-next", "softaworks/agent-toolkit", 1600, "Ship-learn-iterate development methodology for rapid prototyping and feedback.", ["methodology", "shipping", "iteration"]),
  skill("professional-communication", "softaworks/agent-toolkit", 1600, "Draft professional emails, messages, and documents with appropriate tone and structure.", ["communication", "writing", "professional"]),
  skill("command-creator", "softaworks/agent-toolkit", 1600, "Create custom CLI commands and slash commands for agent workflows.", ["cli", "commands", "tooling"]),
  skill("marp-slide", "softaworks/agent-toolkit", 1600, "Create presentation slides using Marp markdown-to-slide framework.", ["marp", "slides", "presentation"]),
  skill("plugin-forge", "softaworks/agent-toolkit", 1600, "Build and publish agent plugins with proper structure and marketplace integration.", ["plugins", "agent", "development"]),
  skill("feedback-mastery", "softaworks/agent-toolkit", 1600, "Give and process constructive feedback for code, design, and product decisions.", ["feedback", "collaboration", "communication"]),
  skill("humanizer", "softaworks/agent-toolkit", 1600, "Transform AI-generated text into natural, human-like writing with authentic voice.", ["writing", "humanizer", "content"]),
  skill("c4-architecture", "softaworks/agent-toolkit", 1600, "Create C4 model architecture diagrams with context, container, component views.", ["architecture", "c4", "diagrams"]),
  skill("event-store-design", "wshobson/agents", 1500, "Design event stores with CQRS, event sourcing, and projection patterns.", ["event-sourcing", "cqrs", "backend"]),
  skill("baseline-ui", "ibelick/ui-skills", 1500, "Build baseline UI components following design system foundations and best practices.", ["ui", "components", "design-system"]),
  skill("cost-optimization", "wshobson/agents", 1500, "Optimize cloud infrastructure costs with rightsizing, reserved capacity, and monitoring.", ["cloud", "cost", "optimization"]),
  skill("go-concurrency-patterns", "wshobson/agents", 1500, "Write concurrent Go programs with goroutines, channels, and synchronization patterns.", ["go", "concurrency", "patterns"]),
  skill("threejs-animation", "cloudai-x/threejs-skills", 1500, "Animate 3D scenes with Three.js keyframes, skeletal animation, and morph targets.", ["threejs", "animation", "3d"]),
  skill("clean-code", "sickn33/antigravity-awesome-skills", 1500, "Apply clean code principles for readable, maintainable, and testable software.", ["clean-code", "best-practices", "quality"]),
  skill("security-requirement-extraction", "wshobson/agents", 1500, "Extract security requirements from specifications and create threat models.", ["security", "requirements", "threat-model"]),
  skill("cqrs-implementation", "wshobson/agents", 1500, "Implement CQRS pattern with command and query separation for scalable systems.", ["cqrs", "architecture", "patterns"]),
  skill("wcag-audit-patterns", "wshobson/agents", 1500, "Audit web applications for WCAG 2.2 accessibility compliance with structured reports.", ["accessibility", "wcag", "audit"]),
  skill("embedding-strategies", "wshobson/agents", 1500, "Choose and implement embedding strategies for semantic search and RAG systems.", ["embeddings", "ai", "search"]),
  skill("context-driven-development", "wshobson/agents", 1500, "Development methodology centered on understanding and leveraging project context.", ["methodology", "context", "development"]),
  skill("fixing-motion-performance", "ibelick/ui-skills", 1500, "Optimize CSS and JS animation performance for smooth 60fps motion.", ["animation", "performance", "css"]),
  skill("dependency-upgrade", "wshobson/agents", 1500, "Plan and execute dependency upgrades with compatibility testing and migration steps.", ["dependencies", "upgrade", "maintenance"]),
  skill("nx-workspace-patterns", "wshobson/agents", 1500, "Configure Nx workspaces for monorepo management with generators and executors.", ["nx", "monorepo", "workspace"]),
] as const;
